version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: env_logger
    versions:
    - 0.8.3
  - dependency-name: once_cell
    versions:
    - 1.7.0
  - dependency-name: ahash
    versions:
    - 0.7.0
    - 0.7.2
  - dependency-name: bstr
    versions:
    - 0.2.15
  - dependency-name: nom
    versions:
    - 6.1.0
    - 6.1.2
  - dependency-name: thiserror
    versions:
    - 1.0.24
  - dependency-name: serde_json
    versions:
    - 1.0.64
  - dependency-name: syn
    versions:
    - 1.0.60
  - dependency-name: log
    versions:
    - 0.4.14
  - dependency-name: derive_setters
    versions:
    - 0.1.5
  - dependency-name: predicates
    versions:
    - 1.0.7
  - dependency-name: proc-exit
    versions:
    - 1.0.2
