[package]
name = "typos"
version = "0.1.0"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Source Code Spelling Correction"
repository = "https://github.com/epage/typos"
documentation = "https://docs.rs/typos"
readme = "README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "epage/typos" }
appveyor  = { repository = "epage/typos" }

[features]
# Support quickly iterating
iterate_unstable = []

[dependencies]
failure = "0.1"
structopt = "0.2"
clap = "2"
ignore = "0.4"
phf = { version = "0.7", features = ["unicase"] }
regex = "1.0"
lazy_static = "1.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
itertools = "0.8"
unicase = "1.1"
bstr = "0.2"

[dev-dependencies]
assert_fs = "0.10"

[build-dependencies]
phf_codegen = "0.7"
csv = "1.0"
unicase = "1.1"
