[package]
name = "varcon"
version = "0.6.0"
description = "Source Code Spelling Correction"
authors = ["Ed Page <eopage@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/crate-ci/typos"
readme = "../../README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
edition = "2018"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[features]
default = ["all"]
all = ["flags"]
flags = ["varcon-core/flags"]

[dependencies]
varcon-core = { version = "^2.0", path = "../varcon-core" }
