[package]
name = "varcon"
version = "0.5.0"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Source Code Spelling Correction"
repository = "https://github.com/crate-ci/typos"
readme = "../../README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
codecov = { repository = "crate-ci/typos" }

[features]
default = ["all"]
all = ["flags"]
flags = ["varcon-core/flags"]

[dependencies]
varcon-core = { version = "^2.0", path = "../varcon-core" }
