[package]
name = "misspell-dict"
version = "0.4.0"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Source Code Spelling Correction"
repository = "https://github.com/crate-ci/typos"
readme = "README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[package.metadata.release]
disable-release = true

[dependencies]
unicase = "2.5"
log = "0.4"
dictgen = { version = "0.1", path = "../dictgen" }
