[package]
name = "typos-dict"
version = "0.6.2"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Source Code Spelling Correction"
repository = "https://github.com/crate-ci/typos"
readme = "../../README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
codecov = { repository = "crate-ci/typos" }

[dependencies]
unicase = "2.5"
log = "0.4"
dictgen = { version = "0.1", path = "../dictgen" }
