[package]
name = "typos-dict"
version = "0.8.2"
description = "Source Code Spelling Correction"
authors = ["Ed Page <eopage@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/crate-ci/typos"
readme = "../../README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
edition = "2018"
rust-version = "1.59.0"  # MSRV
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[dependencies]
unicase = "2.5"
log = "0.4"
dictgen = { version = "^0.2", path = "../dictgen" }
