[package]
name = "varcon-core"
version = "2.2.5"
description = "Varcon-relevant data structures"
authors = ["Ed Page <eopage@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/crate-ci/typos"
readme = "../../README.md"
categories = ["text-processing"]
edition = "2021"
rust-version = "1.64.0"  # MSRV
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[features]
default = []
parser = ["nom"]
flags = ["enumflags2"]

[dependencies]
nom = { version = "7", optional = true }
enumflags2 = { version = "0.7", optional = true }

[package.metadata.docs.rs]
features = [ "parser", "flags" ]
