[package]
name = "varcon-core"
version = "2.2.7"
description = "Varcon-relevant data structures"
readme = "../../README.md"
categories = ["text-processing"]
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
include.workspace = true

[features]
default = []
parser = ["nom"]
flags = ["enumflags2"]

[dependencies]
nom = { version = "7", optional = true }
enumflags2 = { version = "0.7", optional = true }

[package.metadata.docs.rs]
features = [ "parser", "flags" ]
