[package]
name = "dictgen"
version = "0.2.4"
description = "Compile-time case-insensitive map"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling", "no_std"]
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
include.workspace = true

[features]
default = ["std"]
std = []
codegen = ["std", "phf_codegen"]
map = ["phf", "phf_shared"]

[dependencies]
unicase = "2.6"
phf = { version = "0.11", features = ["unicase"], optional = true }
phf_codegen = { version = "0.11", optional = true }
phf_shared = { version = "0.11", optional = true }
