[package]
name = "dictgen"
version = "0.2.4"
description = "Compile-time case-insensitive map"
repository = "https://github.com/crate-ci/typos"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling", "no_std"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.64.0"  # MSRV
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[features]
default = ["std"]
std = []
codegen = ["std", "phf_codegen"]
map = ["phf", "phf_shared"]

[dependencies]
unicase = "2.6"
phf = { version = "0.11", features = ["unicase"], optional = true }
phf_codegen = { version = "0.11", optional = true }
phf_shared = { version = "0.11", optional = true }
