[package]
name = "wikipedia-dict"
version = "0.4.0"
description = "Source Code Spelling Correction"
authors = ["Ed Page <eopage@gmail.com>"]
license = "CC-BY-SA-3.0"
repository = "https://github.com/crate-ci/typos"
readme = "README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
edition = "2018"
publish = false
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[package.metadata.release]
release = false

[dependencies]
unicase = "2.5"
dictgen = { version = "^0.2", path = "../dictgen" }
