name: codegen
on:
  pull_request:
    paths:
    - 'Cargo.lock'
    - '**/codegen/**'
    - '**/verify/**'
    - '**/*codegen.rs'
  push:
    branches:
    - master
    paths:
    - 'Cargo.lock'
    - '**/codegen/**'
    - '**/verify/**'
    - '**/*codegen.rs'
  schedule:
  - cron: '9 9 9 * *'
jobs:
  codegen:
    name: Verify Code-gen
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.53.0  # MSRV
        profile: minimal
        override: true
    - uses: Swatinem/rust-cache@v1
    - name: Verify typos-dict
      run: |
        cargo run --package typos-dict-codegen -- --output crates/typos-dict/src/dict_codegen.rs --check
    - name: Verify typos-vars
      run: |
        cargo run --package typos-vars-codegen -- --output crates/typos-vars/src/vars_codegen.rs --check
    - name: Verify typos-dict-verify
      run: |
        cargo run --package typos-dict-verify -- --input crates/typos-dict/assets/words.csv --output crates/typos-dict/assets/words.csv --check
    - name: Verify codespell-dict
      run: |
        cargo run --package codespell-codegen -- --output crates/codespell-dict/src/dict_codegen.rs --check
    - name: Verify misspell-dict
      run: |
        cargo run --package misspell-codegen -- --output crates/misspell-dict/src/dict_codegen.rs --check
    - name: Verify wikipedia-dict
      run: |
        cargo run --package wikipedia-codegen -- --output crates/wikipedia-dict/src/dict_codegen.rs --check
    - name: Verify varcon-dict
      run: |
        cargo run --package varcon-codegen -- --output crates/varcon/src/codegen.rs --check
